services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/conf.d:/etc/postgresql/conf.d

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    depends_on: [postgres]
    ports: ["9187:9187"]

  node-exporter:
    image: prom/node-exporter
    restart: unless-stopped
    ports: ["9100:9100"]

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    ports: ["9090:9090"]
    depends_on: [postgres-exporter, node-exporter]

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports: ["3000:3000"]
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
    depends_on: [prometheus]
